pro_ops/app_ops/urls.py
from django.urls import include,path,re_path
from django.conf import settings
from django.conf.urls.static import static
from . import (
    views,
    server_views,
    dml_views,
    os_views,
    user_views,
    doc_views,
    cmanage_views,
)

urlpatterns = [
    path('', views.main),
    path('login/',views.login_in),
    path('logout/',views.login_out),
    path('main/',views.main),
    path('doc/create_project/',doc_views.create_project),
    path('doc/create_dir/',doc_views.create_dir),
    path('doc/list_dir/',doc_views.list_dir),
    path('doc/rename/',doc_views.rename),
    path('doc/delete/',doc_views.del_dir_or_file),
    path('doc/update_group/',doc_views.update_group),
    path('doc/update_perm/',doc_views.update_perm),
    path('doc/get_perms/',doc_views.get_perms),
    path('cmanage/',cmanage_views.cmanage_list),
    path('cmanage/add_order/',cmanage_views.add_order),
    path('user_manager/',user_views.user_list),
    path('server/',server_views.get_list),
    path('server/export/',server_views.export_excel),
    path('os/',os_views.get_list),
    path('os/export/',os_views.export_excel),
    path('dml/',dml_views.dml),
    path('doc/perms/',doc_views.perms),
    re_path(r'^doc/add_or_edit/([0-9]*)',doc_views.add_or_edit),
     re_path(r'^doc/add_or_edit_group/([0-9]*)',doc_views.add_or_edit_group),
    re_path(r'^doc/([0-9]*)',doc_views.doc),
    re_path(r'^os/add_or_edit_os/([0-9]*)',os_views.add_or_edit),
    re_path(r'^server/add_or_edit_server/([0-9]*)',server_views.add_or_edit),
    re_path(r'^user_detail/([0-9]*)',user_views.user_detail),
    re_path(r'^change_pd_or_perm/([0-9]*)',user_views.change_pd_or_perm),
    re_path(r'^del_user/([0-9]*)',user_views.del_user),
] + static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

pro_ops/pro_ops/urls.py
from django.contrib import admin
from django.urls import path,include
#from app_ops import views as ops_views

urlpatterns = [
    path("ops/",include('app_ops.urls'), name="ops"),
#    path("",ops_views.index, name="name"),
    #path('admin/', admin.site.urls),
]

pro_ops/app_ops/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Server(models.Model):
    productid = models.CharField(unique=True,max_length=20)
    brand = models.CharField(max_length=20)
    servername = models.CharField(max_length=50)
    model = models.CharField(max_length=50)    
    status = models.CharField(max_length=20)
    cpu_model = models.CharField(null=True,blank=True,max_length=50)
    cpu_quantity = models.CharField(max_length=10)
    cpu_core = models.CharField(max_length=10)
    memory_quantity = models.CharField(max_length=10)
    memory_total = models.CharField(max_length=10)
    ssd_quantity = models.CharField(blank=True,null=True,max_length=10)
    ssd_total = models.CharField(blank=True,null=True,max_length=10)
    hdd_quantity = models.CharField(blank=True,null=True,max_length=10)
    hdd_total = models.CharField(blank=True,null=True,max_length=10)
    raid_type = models.CharField(blank=True,null=True,max_length=10)   
    idrac_ip = models.CharField(blank=True,null=True,max_length=20)
    purchase_date = models.CharField(blank=True,null=True,max_length=20)
    warranty_end = models.CharField(blank=True,null=True,max_length=20)   
    function = models.CharField(blank=True,null=True,max_length=50)
    data_center = models.CharField(max_length=20)
    network = models.CharField(blank=True,null=True,max_length=100)
    idrac_network = models.CharField(blank=True,null=True,max_length=100)
    rack = models.CharField(max_length=10)
    rack_u = models.CharField(max_length=10)

class Os(models.Model):
    productid = models.CharField(blank=True,null=True,max_length=20)
    server_type = models.CharField(blank=True,null=True,max_length=10)
    hostname = models.CharField(blank=True,null=True,max_length=50)
    system_version = models.CharField(blank=True,null=True,max_length=50)    
    status = models.CharField(blank=True,null=True,max_length=10)
    kernel = models.CharField(null=True,blank=True,max_length=50)
    core_quantity = models.CharField(blank=True,null=True,max_length=10)
    memory = models.CharField(blank=True,null=True,max_length=10)
    hdd = models.CharField(blank=True,null=True,max_length=10)
    vlan = models.CharField(blank=True,null=True,max_length=10)
    ip = models.CharField(unique=True,max_length=20)
    esxi_ip = models.CharField(blank=True,null=True,max_length=20)
    zbx_stau = models.CharField(blank=True,null=True,max_length=20)
    application = models.CharField(blank=True,null=True,max_length=100)
    administrator = models.CharField(blank=True,null=True,max_length=50)
    remarks = models.CharField(blank=True,null=True,max_length=100)

class Doc(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    text = models.TextField()
    author = models.CharField(max_length=20)
    createtime = models.CharField(max_length=20)
    editortime = models.CharField(blank=True,null=True,max_length=20)

class Cmanage(models.Model):
    title = models.CharField(max_length=50) 
    content = models.TextField()
    effect = models.CharField(max_length=100)
    rollback = models.CharField(max_length=100)
    statu = models.CharField(max_length=10)
    author = models.CharField(max_length=20)
    cdate = models.DateField(auto_now_add=True)        #工单创建日期
    ctime = models.CharField(max_length=20)            #工单创建时间
    witime = models.CharField(max_length=50)           #变更窗口时间
    end_time = models.CharField(max_length=20)         #实际变更结束时间
    reviewer = models.CharField(max_length=20)         #核查人
    confirm = models.CharField(max_length=100)         #

class Directory(models.Model):
    dirname = models.CharField(max_length=50)
    grade = models.IntegerField()
    parentid = models.IntegerField()
    class Meta:
        unique_together=('dirname','grade')

class Document(models.Model):
    filename = models.CharField(max_length=50)
    filepath = models.CharField(max_length=50)
    directory = models.ForeignKey(Directory, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    createtime = models.CharField(max_length=20)
    editortime = models.CharField(blank=True,null=True,max_length=20)
    class Meta:
        unique_together=('directory','filename')

class Progroup(models.Model):
    group = models.CharField(max_length=20)                         #用户组名称

class Usergroup(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Progroup, on_delete=models.CASCADE)
    label = models.IntegerField()                                   #0成员，1属主

class Properm(models.Model):
    project = models.ForeignKey(Directory, on_delete=models.CASCADE)            #项目id                     
    group = models.ForeignKey(Progroup, on_delete=models.CASCADE)               #用户组id
    perm = models.CharField(max_length=5)                                       #view查看，edit编辑，owner属主

class Personal(models.Model):
    project = models.ForeignKey(Directory, on_delete=models.CASCADE)            #项目id
    user = models.ForeignKey(User, on_delete=models.CASCADE)                    #用户id

pro_ops/app_ops/views.py
from django.shortcuts import render,redirect
import ast
from django.http import HttpResponse,JsonResponse
# Create your views here.
from django.db.models import Count
from django.http import HttpResponse
from django.db import models
from .models import Server,Os,Doc,Cmanage
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from functools import wraps
from django.contrib.auth.models import ContentType, Permission, User
from django.contrib.auth import authenticate, login, logout
from .check_login_views import check_login

def login_in(request):
    if request.method == 'GET':
        return render(request,'ops/login.html')
    else:
        ss_name = request.POST.get('user_name')
        ss_password = request.POST.get('user_password')
        
        user = authenticate(username=ss_name, password=ss_password)
        if user is not None and user.is_active:
            login(request,user)
            request.session['login'] = "success"
            request.session['username'] = user.username
            request.session['user_id'] = user.id
            request.session['fullname'] = user.first_name
            # request.session.set_expiry(60)
            msg = {
                'code': '200',
            }
            return JsonResponse(msg)
        else:
            msg = {
                'code': '400',
                'tips' :'用户不存在或密码错误',
            }
            return JsonResponse(msg)

def login_out(request):
    logout(request)
    return redirect('/ops/login/')

@check_login
def main(request):
    fullname = request.session['fullname']
    user_id = request.session['user_id']
    
    d1 = Server.objects.filter(data_center='总部6F').count()
    d2 = Server.objects.filter(data_center='总部7F').count()
    d3 = Server.objects.filter(data_center='新化').count()
    d4 = Server.objects.filter(data_center='日业').count()
    d5 = Server.objects.filter(data_center='鑫远').count()
    d6 = Server.objects.filter(data_center='公园道').count()
    dt = [d1,d2,d3,d4,d5,d6]

    o1 = Os.objects.filter(system_version__icontains='centos').count()
    o2 = Os.objects.filter(system_version__icontains='windows').count()
    o3 = Os.objects.filter(system_version__icontains='esxi').count()
    o4 = Os.objects.filter(system_version='').count()
    ot = {"Esxi":o3,"Linux":o1,"Windows":o2,"Others":o4}

    return render(request,'ops/main.html',{'fullname':fullname,'data':dt,'ot':ot,'user_id': user_id,})

pro_ops/app_ops/templates/ops/Base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>运维管理平台</title>
    <script src="/static/js/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/base.css">
    {% block style %}
    {% endblock %}
</head>

<body>
    <div>
        <ul class="list">
            <!-- <li><img src="/static/img/home.png" alt=""></li> -->
            <li id="li_main"><a href="/ops/main/">主页</a></li>
            {% if perms.app_ops.view_server %}
            <li id="li_server"><a href="/ops/server/">服务器</a></li>
            {% endif %}
            {% if perms.app_ops.view_os %}
            <li id="li_os"><a href="/ops/os/">操作系统</a></li>
            {% endif %}
            {% if perms.app_ops.view_cmanage %}
            <li id="li_cmanage"><a href="/ops/cmanage/">变更管理</a></li>
            {% endif %}
            {% if perms.app_ops.view_doc %}
            <li id="li_doc"><a href="/ops/doc/">文档中心</a></li>
            {% endif %}
            {% if perms.view_user %}
            <li id="li_user_manager"><a href="/ops/user_manager">用户管理</a></li>
            {% endif %}
            <li id="li_user" style="float: right;" class="dropdown"><a href="#">你好，{{user.first_name}}</a>  
                <div class="dropdown-content" style="position: absolute;">
                    <a href="/ops/user_detail/{{user_id}}/" style="padding: 6px 8px;" >修改密码</a>
                    <a href="/ops/logout/" style="padding: 6px 8px;">注销</a>
                </div>
            </li>
        </ul>
        
    </div>

    
    <!-- <div id="blk_hidden"><p id="p_hidden"><img src="/static/img/left.png" alt=""></p></div> -->
    <div class="bk_base">      
        {% block content %}
        {% endblock %}
    </div>
    <!-- <script>
        $("#blk_hidden").click(function(){
            var statu = $(".list").css("display")
            if (statu == "none"){
                $(".list").css("display","block")
                $("#blk_hidden").css("left","200px")
                $(".bk_base").css("left","210px")
            }
            else{
                $(".list").css("display","none")
                $("#blk_hidden").css("left","0")
                $(".bk_base").css("left","10px")
            }
        })
    </script> -->
</body>
</html>

pro_ops/app_ops/templates/ops/add_or_edit_doc.html
{% extends "ops/Base.html" %}
{% block style %}
<script type="text/javascript" src="//unpkg.com/wangeditor/dist/wangEditor.min.js"></script>
{% endblock %}

{% block content %}
<h5 id="h5_id">新增文档</h5>
<div id="container">
    <div id="doc_editor"></div>
        <br>
        <div class="btn_set_add">
            &emsp;&emsp;<button id="add_doc_btn_save">保存</button>
            &emsp;&emsp;<button id="add_doc_btn_return">返回</button>
        </div>
</div>

<script>
    var doc_id = '{{doc_id}}'
    const E = window.wangEditor
    const editor = new E('#doc_editor')
    editor.config.height = 700
    editor.create()
    editor.txt.html('{{doc_content|safe}}')
    $("#add_doc_btn_save").click(function(){
        doc_content = editor.txt.html()
        $.ajax({
            type:"POST",
            url: "/ops/doc/add_or_edit/"+doc_id,
            traditional:true,
            data:{id: doc_id, content: doc_content,  csrfmiddlewaretoken: '{{ csrf_token }}',},
            success:function(submit){
                if (submit.code == 0){
                    alert('保存成功')
                }else{
                    alert('保存失败')
                }
            }
        })
    })
    $("#add_doc_btn_return").click(function(){
        url = '/ops/doc/'
        window.location.href = url
    })
</script>
{% endblock %}



pro_ops/app_ops/templates/ops/add_or_edit_server.html
{% extends "ops/Base.html" %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="/static/css/alter.css">
{% endblock %}

{% block content %}     
    
<h5 id="h5_id">{% if info.id %}编辑{% else %}新增{% endif %}</h5>
    <form id="content" method="POST">
        {%csrf_token%}         
            <table class="a">
            <tr>
                <td>产品编号：</td>
                <td style="width:200px"><input type="text" name="productid" value="{{info.productid}}" autocomplete="off"></td>
                <td>设备品牌：</td>
                <td style="width:200px"><input type="text" name="brand" value="{{info.brand}}" autocomplete="off"></td>
            </tr>
            <tr>
                <td>设备名称：</td>
                <td><input type="text" name="servername" value="{{info.servername}}" autocomplete="off"></td>
                <td>设备型号：</td>
                <td><input type="text" name="model" value="{{info.model}}" autocomplete="off"></td>
            </tr>
            <tr>
                <td>设备状态：</td>
                <td><input type="text" name="status" value="{{info.status}}" autocomplete="off"></td>
                <td>CPU型号：</td>
                <td><input type="text" name="cpu_model" value="{{info.cpu_model}}" autocomplete="off"></td>
            </tr>
            <tr>
                <td>CPU颗数：</td>
                <td><input type="text" name="cpu_quantity" value="{{info.cpu_quantity}}" autocomplete="off"></td>
                <td>CPU核心：</td>
                <td><input type="text" name="cpu_core" value="{{info.cpu_core}}" autocomplete="off"></td>
            </tr> 
            <tr>
                <td>内存数量：</td>
                <td><input type="text" name="memory_quantity" value="{{info.memory_quantity}}" autocomplete="off"></td>
                <td>内存总量(GB)：</td>
                <td><input type="text" name="memory_total" value="{{info.memory_total}}" autocomplete="off"></td>
            </tr>
            <tr>
                <td>SSD数量：</td>
                <td><input type="text" name="ssd_quantity" value="{{info.ssd_quantity}}" autocomplete="off"></td>
                <td>SSD总量(GB)：</td>
                <td><input type="text" name="ssd_total" value="{{info.ssd_total}}" autocomplete="off"></td>
            </tr>
            <tr>
                <td>HDD数量：</td>
                <td><input type="text" name="hdd_quantity" value="{{info.hdd_quantity}}" autocomplete="off"></td>
                <td>HDD总量(TB)：</td>
                <td><input type="text" name="hdd_total" value="{{info.hdd_total}}" autocomplete="off"></td>
            </tr>
            <tr>
                <td>raid模式：</td>
                <td><input type="text" name="raid_type" value="{{info.raid_type}}" autocomplete="off"></td>
                <td>IDRAC IP：</td>
                <td><input type="text" name="idrac_ip" value="{{info.idrac_ip}}" autocomplete="off"></td>
            </tr>
            <tr>
                <td>购买日期：</td>
                <td><input type="text" name="purchase_date" value="{{info.purchase_date}}" autocomplete="off"></td>
                <td>质保终止：</td>
                <td><input type="text" name="warranty_end" value="{{info.warranty_end}}" autocomplete="off"></td>
            </tr>
            <tr>
                <td>设备功能：</td>
                <td><input type="text" name="function" value="{{info.function}}" autocomplete="off"></td>
                <td>数据中心：</td>
                <td><input type="text" name="data_center" value="{{info.data_center}}" autocomplete="off"></td>
            </tr>
            <tr>
                <td>网络接入：</td>
                <td><input type="text" name="network" value="{{info.network}}" autocomplete="off"></td>
                <td>idrac网络接入：</td>
                <td><input type="text" name="idrac_network" value="{{info.idrac_network}}" autocomplete="off"></td>
            </tr>
            <tr>
                <td>机柜位置：</td>
                <td><input type="text" name="rack" value="{{info.rack}}" autocomplete="off"></td>
                <td>具体U位：</td>
                <td><input type="text" name="rack_u" value="{{info.rack_u}}" autocomplete="off"></td>
            </tr>
            <tr style="display: none;">
                <td><input type="text" name="mod" value="Server"></td>
                <td><input type="text" name="id" {% if info.id %}value="{{info.id}}"{% else %}value="0"{% endif %}></td>
            </tr>
            </table>
        
            <br>
            <br>
            <button style="margin-left: 380px;" type="reset">清除</button>
            <button style="margin-left: 20px;" type="button" id="btn_commit">提交</button>
            <a class="re" href="/ops/server/" style="text-decoration: none;margin-left: 20px;"><button type="button">返回</button></a>         
    </form> 

    <script>
        $("#li_server").css("background-color","rgb(46, 50, 54)")
        $("#li_server a").css("color","white")

        $("#btn_commit").click(function(){
            var from_data = $("#content").serializeArray();
            $.ajax({
                url: '/ops/dml/',
                type:'post',
                data:from_data,
                success:function(submit){
                    if (submit.code == 200){
                        alert(submit.msg)
                        window.location.href = "/ops/server/add_or_edit_server/"
                    }
                    else{
                        alert(submit.msg)
                    }
                }
            })
        })
    </script>
{% endblock %}

pro_ops/app_ops/templates/ops/details.html
{% extends "ops/Base.html" %}
{% block style %}
<link rel="stylesheet" type="text/css" href="/static/css/details.css">

{% endblock %}
     
{% block content %}
<h5 id="h5_id">文档详情</h5>
    <div id="container">
        <div id="bk_title">
           <h4>{{info.title}}</h4>
        </div>

            <div class="tag">
                <p>
                    <span>作者：{{info.author}}</span>
                </p>
                <p>
                    <span>创建时间：{{info.createtime}}</span>
                </p>
                <p>
                    <span>最新编辑时间：{{info.editortime}}</span>
                </p>
            </div>

        <div id="bk_content">
            <div id="notetext">{{info.content}}</div>   
        </div>
        <br>
        <div class="bk_alter">
            {% if perms.app_ops.change_doc %}
            <a href="/ops/doc/add_or_edit_doc/{{info.id}}/"><button class="editor">修改</button></a>
            {% endif %}
            {% if perms.app_ops.delete_doc %}
            &emsp;&emsp;<button class="editor" id="btn_del">删除</button>
            {% endif %}
        </div>
       
    </div>

    <script type="text/javascript">
        $("#li_doc").css("background-color","rgb(46, 50, 54)")
        $("#li_doc a").css("color","white")

        var obj = document.getElementById("notetext");
        obj.innerHTML = obj.innerText;//这样重新设置html代码为解析后的格式
 
        $("#btn_del").click(function(){
            url = "/ops/dml/?id="+'{{info.id}}&mod=Doc'
            $.getJSON(url,function(status){
                if(status.code == 0){
                    alert("删除成功")
                    window.location.href = "/ops/doc/"
                }
                else{
                    alert("操作失败")
                }
            })
        })
    </script>

{% endblock %}



pro_ops/app_ops/templates/ops/os.html
{% extends "ops/Base.html" %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="/static/css/os.css">
{% endblock %}

{% block content %}
<h5 id="h5_id">操作系统列表</h5>
    <form action="", method="GET"> 
        <table class="a">
            <tr>
                <td>产品编号：</td>   
                <td style="width:200px"><input type="text" name="productid" class="ipt_os_query" value="{{productid}}" autocomplete="off"></td> 
                <td>主机名：</td>
                <td style="width:200px"><input type="text" name="hostname" class="ipt_os_query" value="{{hostname}}" autocomplete="off"></td style="">
                <td>操作系统：</td>
                <td>
                    <input list="os_list" name="system_version" class="ipt_os_query" value="{{system_version}}" autocomplete="off">
                    <datalist id="os_list">
                        <option value="VMware ESXI 6.5">
                        <option value="VMware ESXI 6.0">
                        <option value="Centos 7">
                        <option value="Ubuntu 16.04">
                        <option value="Ubuntu 18.08">
                        <option value="Windows Server 2008 R2">
                        <option value="Windows Server 2012 R2">
                        <option value="windows 7">
                    </datalist>
                </td>
            <tr>
                <td>IP：</td>
                <td><input type="text" name="ip" class="ipt_os_query" value="{{ip}}" autocomplete="off"></td>
                <td>宿主机：</td>
                <td><input type="text" name="esxi_ip" class="ipt_os_query" value="{{esxi_ip}}" autocomplete="off"></td>
                <td>机器类型：</td>
                <td>
                    <input list="type_list" name="server_type" class="ipt_os_query" value="{{server_type}}" autocomplete="off">
                    <datalist id="type_list">
                        <option value="物理机">
                        <option value="虚拟机">
                    </datalist>
                </td>   
            </tr>
        </table>
        <br>
        <div class="blk_btn_set">
            {% if perms.app_ops.add_os %}
            <a style="text-decoration: none;" href="/ops/os/add_or_edit_os/"><button type="button" >新增</button></a>
            {%  endif %}
            {% if perms.app_ops.change_os %}
            <button name="alter" id="alter_os" type="button">更改</button>
            {%  endif %}
            {% if perms.app_ops.delete_os %}
            <button name="delete" type="button" id="os_btn_del">删除</button>
            {%  endif %}
            <button style="margin-left: 20px;" name="btn_submit" value="select">查询</button>
            <button name="btn_submit"  value="pre">上一页</button>
            <button name="btn_submit"  value="next">下一页</button>
            <button name="btn_submit" value="st_number">跳至</button>
            <input style="width: 80px; height: 15px;" type="number" name="page_number" autocomplete="off">
            &ensp;<span style="font-size: 9pt;">{{page_number}} / {{number}}</span>
            &ensp;&ensp;<span style="font-size: 9pt;">共 {{count}} 条</span>
            {% if perms.app_ops.add_os %}
            &emsp;&emsp;&emsp;&emsp;<a href="/ops/os/export/"><button type="button">全部导出</button></a>
            {%  endif %}
        </div>   
    </form>
    <br>
    
    <div style="width: 100%; overflow-x: auto;white-space: nowrap;">
        <table class="tb" id="tb_os">
            <tr>
                <th><input type="checkbox" id="all_box"></th>
                <th>序号</th>
                <th>产品编号</th>
                <th>机器类型</th>
                <th>主机名</th>
                <th>操作系统</th>
                <th>状态</th>
                <th>内核信息</th>
                <th>CPU核心</th>
                <th>内存</th>
                <th>硬盘</th>
                <th>vlan</th>
                <th>IP</th>
                <th>宿主机</th>
                <th>监控状态</th>
                <th>应用信息</th>
                <th>应用负责人</th>
                <th>备注</th>
            </tr>
            {% for os in list2 %}
            <tr>
                <td class="td_box"><input type="checkbox" class="box" id="{{ forloop.counter}}" value="{{ os.id }}" onclick="unselect_all(this)"></td>
                <td class="data">{{ forloop.counter|add:strat }}</td>
                <td class="data">{{ os.productid }}</td>
                <td class="data">{{ os.server_type }}</td>
                <td class="data">{{ os.hostname }}</td>
                <td class="data">{{ os.system_version }}</td>
                <td class="data">{{ os.status }}</td>
                <td class="data">{{ os.kernel }}</td>
                <td class="data">{{ os.core_quantity }}</td>
                <td class="data">{{ os.memory }}</td>
                <td class="data">{{ os.hdd }}</td>
                <td class="data">{{ os.vlan }}</td>
                <td class="data">{{ os.ip }}</td>
                <td class="data">{{ os.esxi_ip }}</td>
                <td class="zabbix">
                    <label class="switch">
                        <input type="checkbox" tag="{{os.ip}}" class="zabbix_status"  {% ifequal os.zbx_stau 'on' %}checked{%endifequal%}> 
                        <div class="slider">
                            <span class="on">on</span>
                            <span class="off">off</span>
                        </div>
                    </label>
                </td>
                <td class="data">{{ os.application }}</td>
                <td class="data">{{ os.administrator }}</td>
                <td class="data">{{ os.remarks }}</td>
            </tr>
            {% endfor %}
        </table>
    </div> 
    <script>
        $("#li_os").css("background-color","rgb(46, 50, 54)");  //设置当前导航栏选项背景涂色
        $("#li_os a").css("color","white");
        //设置复选框全选和反选，以及涂色
        $("#all_box").click(function(){
            var x = $(this).prop("checked")
            $(".box").prop("checked",x)
            if(x == true){
                $("table.tb td").css("background-color", "rgb(209, 215, 223)");
            }
            else{
                $("table.tb td").css("background-color", "#FFFFFF");
            }
        })
        
        //判断是否满足全选
        $(".box").click(function(){
            var j = 0
            var le = $(".box").length
            $(".box").each(function(){
                var status = $(this).prop("checked")
                if (status == true){
                    j++;
                }
            })
            if(j<le){
                $("#all_box").prop("checked",false)
            }
            else{
                $("#all_box").prop("checked",true)
            }  
        })

        //删除事件
        var delete_list = []
        $("#os_btn_del").click(function(){
            $(".box").each(function(){
                var status = $(this).prop("checked")
                var id = $(this).val()
                if (status == true){
                    delete_list.push(id)
                }
            })
            url = "/ops/dml/?delete_list="+delete_list.join(',')+'&mod=Os'
            $.getJSON(url,function(status){
                if(status.code == 0){
                    alert("删除成功")
                    window.location.href = "/ops/os/"
                }
                else{
                    alert("操作失败")
                }
            })
        })
        
        //编辑事件
        $("#alter_os").click(function(){
            var j=0
            var alter_id
            $(".box").each(function(){
                var status = $(this).prop("checked")
                var id = $(this).val()
                if (status == true){
                    j++;
                    alter_id = id
                }
            })
            if(j>1 || j==0){
                alert("请仅选择一条数据进行更新！")
            }
            else{
                var url = "/ops/os/add_or_edit_os/"+alter_id
                window.location.href = url
            }
        })

        //zabbix监控按钮设置，
        $("input.zabbix_status").click(function(){
            var zbx_stau
            var st = $(this).prop("checked")
            if (st == true){
                zbx_stau = 'on'
            }
            else{
                zbx_stau = 'off'
            }
            var url='/ops/os/?zbx_stau='+zbx_stau+'&ip='+$(this).attr('tag')
            $.getJSON(url,function(d){
                if (d.code == 200){
                    return true
                }
                else{
                    alert('更改失败')
                    $(this).prop("checked",st)
                }
            })
        })

        //鼠标放置背景色设置
        $(function () {
            var tr = $("#tb_os tr");
            tr.mouseover(function () {
                $(this).css("background-color", "rgb(209, 215, 223)");
                $(this).children("td").css("background-color", "rgb(209, 215, 223)");
            }).mouseout(function () {
                var box =$(this).children().eq(0).find("input").prop("checked")
                if (box == true){
                    $(this).css("background-color", "rgb(209, 215, 223)");
                    $(this).children("td").css("background-color", "rgb(209, 215, 223)");
                }
                else{
                    $(this).css("background-color", "#FFFFFF");
                    $(this).children("td").css("background-color", "#FFFFFF");
                }
            });
        });

        //点击数据行勾选
        $(function () {
            var td = $("#tb_os td");
            td.click(function () {
                var box = $(this).parent().children().eq(0).find("input").prop("checked")
                var el_class = $(this).attr("class")
                if (el_class == 'td_box'){
                    return true
                }
                else{
                    if (box == true){
                    $(this).parent().children().eq(0).find("input").prop("checked",false)
                    }
                    else{
                    $(this).parent().children().eq(0).find("input").prop("checked",true)
                    }
                }
                
            })
        });
    
        //input鼠标离开保存值
        $("input").blur(function(){
                $(this).attr("value",$(this).val());
            })
    </script>

{% endblock %}